.TH OMIKUJI 6 "February 16, 2012"
.SH NAME
omikuji - lookup entries in an omikuji file
.SH SYNOPSIS
omikuji [option]... [filename]...
.SH DESCRIPTION
Omikuji is a replacement for the venerable fortune program.  It reads
a specially formatted file and outputs a random fortune to the
standard output.
.SH OPTIONS
.PP
\fB-C\fP
.br
\fB--listcomments\fP
.RS
Show the comments (if any) from the file.
.RE
.PP
\fB-e encoding\fP
.br
\fB--outputencoding=encoding\fP
.RS
Set the output character encoding if not the default.
.RE
.SH AUTHOR
.PP
Omikuji was written by Jason J. A. Stephenson <jason@sigio.com>.
